# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'antmshelfie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for antmshelfie
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'BatchedBridge',
  ]
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
